### ISSUE TITLE
Stack level too deep error when used on jruby/torquebox

### ISSUE THREAD

**Issue by cimtico** [textacular/textacular#60]
I'm getting a:
SystemStackError
stack level too deep

when using this gem on jruby/torquebox

it seems the error may be occurring due to the respond_to? override on:
textacular (3.2.0) lib/textacular.rb:63:in `respond_to?'

Here is the stacktrace:

```
textacular (3.2.0) lib/textacular.rb:63:in `respond_to?'
torquebox-transactions (3.1.0) lib/torquebox/active_record_adapters.rb:148:in `prepare'
activerecord-jdbc-adapter (1.3.10) lib/arjdbc/jdbc/adapter.rb:79:in `initialize'
activerecord-jdbc-adapter (1.3.10) lib/arjdbc/postgresql/adapter.rb:1320:in `initialize'
activerecord-jdbc-adapter (1.3.10) lib/arjdbc/jdbc/connection_methods.rb:12:in `jdbc_connection'
activerecord-jdbc-adapter (1.3.10) lib/arjdbc/postgresql/connection_methods.rb:45:in `postgresql_connection'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `checkout'
/home/user/torquebox-3.1.1/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/user/torquebox-3.1.1/jruby/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `connection'
/home/user/torquebox-3.1.1/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/user/torquebox-3.1.1/jruby/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
activerecord (4.0.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
activerecord (4.0.6) lib/active_record/connection_handling.rb:79:in `retrieve_connection'
activerecord (4.0.6) lib/active_record/connection_handling.rb:53:in `connection'
activerecord (4.0.6) lib/active_record/model_schema.rb:208:in `columns'
textacular (3.2.0) lib/textacular.rb:63:in `respond_to?'
```

It seems the override is done for dynamic matchers (it geves me the feeling of rails 2 dynamic matchers though I could be wrong). If it is in place for older rails versions, it might be better to set it to check for the rails version instead of overriding permanently.

**Comment by gregmolnar** [comment]
@simi This is one thing we should do before the next major release. Drop the deprecated methods. If you have the time and you are willing to do this it would be a great help.

**Comment by simi** [comment]
dropped in #82

**Comment by benhamill** [comment]
This is done, then, right?

**Comment by gregmolnar** [comment]
@benhamill yes. done and merged to master. Thanks for closing it.
