### ISSUE TITLE
Question: Getting IDs

### ISSUE THREAD

**Issue by rstacruz** [textacular/textacular#86]
Is it possible to just get the ID's of the result set?

```rb
search = Question.advanced_search(title: 'how do i derp')
ids = search.select(:id)
```

```
     ActiveRecord::StatementInvalid:
       PG::SyntaxError: ERROR:  subquery has too many columns
```

Using `.pluck` isn't good either.

**Comment by gregmolnar** [comment]
It should be possible. Can you create a simple failing test for me with your models based on this testfile?
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

Thank you!

**Comment by simi** [comment]
`select` works on master, but `pluck` is still broken

```ruby
[6] pry(#<BugTest>)> Restaurant.basic_search('Restaurant').select(:id)
D, [2020-03-01T20:46:08.845019 #380685] DEBUG -- :   Restaurant Load (0.6ms)  SELECT "restaurants".*, COALESCE(ts_rank(to_tsvector('english', "restaurants"."name"::text), plainto_tsquery('english', 'Restaurant'::text)), 0) + COALESCE(ts_rank(to_tsvector('english', "restaurants"."username"::text), plainto_tsquery('english', 'Restaurant'::text)), 0) + COALESCE(ts_rank(to_tsvector('english', "restaurants"."city"::text), plainto_tsquery('english', 'Restaurant'::text)), 0) AS "rank85351130827808291", "restaurants"."id" FROM "restaurants" WHERE (to_tsvector('english', "restaurants"."name"::text) @@ plainto_tsquery('english', 'Restaurant'::text) OR to_tsvector('english', "restaurants"."username"::text) @@ plainto_tsquery('english', 'Restaurant'::text) OR to_tsvector('english', "restaurants"."city"::text) @@ plainto_tsquery('english', 'Restaurant'::text)) ORDER BY "rank85351130827808291" DESC
=> [#<Restaurant:0x000055b1a5eaab08 id: 1, name: "Restaurant Bracerie Marciano", username: nil, city: "Crevoladossola">]



[7] pry(#<BugTest>)> Restaurant.basic_search('Restaurant').pluck(:id)
D, [2020-03-01T20:46:14.530691 #380685] DEBUG -- :    (1.1ms)  SELECT "restaurants"."id" FROM "restaurants" WHERE (to_tsvector('english', "restaurants"."name"::text) @@ plainto_tsquery('english', 'Restaurant'::text) OR to_tsvector('english', "restaurants"."username"::text) @@ plainto_tsquery('english', 'Restaurant'::text) OR to_tsvector('english', "restaurants"."city"::text) @@ plainto_tsquery('english', 'Restaurant'::text)) ORDER BY "rank3243055019785384" DESC
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "rank3243055019785384" does not exist
LINE 1: ..._tsquery('english', 'Restaurant'::text)) ORDER BY "rank32430...
                                                             ^
from /home/retro/.gem/ruby/2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:668:in `exec_params'
Caused by PG::UndefinedColumn: ERROR:  column "rank3243055019785384" does not exist
LINE 1: ..._tsquery('english', 'Restaurant'::text)) ORDER BY "rank32430...
                                                             ^

from /home/retro/.gem/ruby/2.6.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:668:in `exec_params'

```

**Comment by schmijos** [comment]
Trying to add a note to the README: https://github.com/textacular/textacular/pull/145
