### ISSUE TITLE
Search in associations throws missing FROM-clause entry

### ISSUE THREAD

**Issue by haggen** [textacular/textacular#92]
This:

```
Place.joins(:address).advanced_search(name: q, address: { route: q }).explain
```

Gives me this:

```
  Place Load (2.2ms)  SELECT "places".*, COALESCE(ts_rank(to_tsvector('portuguese', "places"."name"::text), to_tsquery('portuguese', 'moraes'::text)), 0) + COALESCE(ts_rank(to_tsvector('portuguese', "address"."route"::text), to_tsquery('portuguese', 'moraes'::text)), 0) AS "rank40213073888883937" FROM "places" INNER JOIN "addresses" ON "addresses"."id" = "places"."address_id" WHERE (to_tsvector('portuguese', "places"."name"::text) @@ to_tsquery('portuguese', 'moraes'::text) AND to_tsvector('portuguese', "address"."route"::text) @@ to_tsquery('portuguese', 'moraes'::text))  ORDER BY "rank40213073888883937" DESC
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "address"
LINE 1: ..., 0) + COALESCE(ts_rank(to_tsvector('portuguese', "address"....
                                                             ^
: SELECT "places".*, COALESCE(ts_rank(to_tsvector('portuguese', "places"."name"::text), to_tsquery('portuguese', 'moraes'::text)), 0) + COALESCE(ts_rank(to_tsvector('portuguese', "address"."route"::text), to_tsquery('portuguese', 'moraes'::text)), 0) AS "rank40213073888883937" FROM "places" INNER JOIN "addresses" ON "addresses"."id" = "places"."address_id" WHERE (to_tsvector('portuguese', "places"."name"::text) @@ to_tsquery('portuguese', 'moraes'::text) AND to_tsvector('portuguese', "address"."route"::text) @@ to_tsquery('portuguese', 'moraes'::text))  ORDER BY "rank40213073888883937" DESC
	from /usr/local/bundle/gems/rack-mini-profiler-0.10.1/lib/patches/db/pg.rb:90:in `exec'
	from /usr/local/bundle/gems/rack-mini-profiler-0.10.1/lib/patches/db/pg.rb:90:in `async_exec'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/querying.rb:39:in `find_by_sql'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/relation.rb:639:in `exec_queries'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/relation.rb:238:in `block in explain'
	from /usr/local/bundle/gems/activerecord-4.2.7/lib/active_record/explain.rb:10:in `collecting_queries_for_explain'
... 3 levels...
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
	from /shared/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I'm using Rails 4.2.7 and PostgreSQL 9.5.3.

**Comment by haggen** [comment]
Now I see it. I must use the name of the table instead of the relation. So it would be:

```ruby
Place.joins(:address).advanced_search(name: 'moraes', addresses: { route: 'moraes' }).explain
```

That's a little confusing. The standard wouldn't be to use the relation name?

**Comment by gregmolnar** [comment]
I agree, it would be better to use the relation name, but that means a non-bc change to textacular. Once I got some free time, I will change this and deprecate the use of table name.

**Comment by andrewhamon** [comment]
This is how it works in normal ActiveRecord where clauses as well:

```ruby
BlogPost.joins(:user).where(users: { username: 'foobar' })
```

Even if the relation to users was called something else, like `author`, its still plural users when querying the users table:
```ruby
BlogPost.joins(:author).where(users: { username: 'foobar' })
```

I think it would be more confusing for experienced Rails devs to break consistency with ActiveRecord.

**Comment by haggen** [comment]
`#joins` uses the relation name, but `#where` uses the table name. I can't tell what's the standard anymore. I'd say there's no issue then.

**Comment by andrewhamon** [comment]
My speculation (since I haven't read the AR source) is that '#joins' needs to know the relation to do the join properly (since you can configure the foreign keys and whatnot) but '#where' doesn't need as much information to translate a Ruby hash to a SQL where clause.

**Comment by simi** [comment]
:thinking: Would better README with example on relation search fix this?
